apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: user10.azurecr.io/reservation:latest
          ports:
            - containerPort: 8080
          envFrom: 
            - configMapRef:
                name: reservation
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: volume
              mountPath: "/apps/data"
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: reservation-pvc